version: "3.8"
services:

  torproxy:
    image: dperson/torproxy
    container_name: torproxy
    ports:
      - 9050:9050
      - 9051:9051
    environment:
      - PASSWORD=test1234
    restart: always
