name: CI Main
on:
  push:
    branches:
      - main

jobs:
  publish:
    environment: Deployment
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9.6 ]
        poetry-version: [ 1.1.5 ]
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install deps
        run: poetry install -vv
      - name: Build and publish
        run: |
          poetry build
          poetry publish --username ${{ secrets.PYPI_USER }} --password ${{ secrets.PYPI_PASS }}
